version: '3.8'

services:
  web:
    build:
      context: ./  # Ensure the 'web' directory exists in the root of your repository
    ports:
      - "80:80"  # Expose port 80 on the host to port 80 in the container
    volumes:
      - ./web:/usr/share/nginx/html  # Mount the 'web' directory to the container
    depends_on:
      db:
        condition: service_healthy  # Ensure DB is fully ready before starting web
    networks:
      - mynetwork  # Connect to the custom network
  
  db:
    image: mysql:8.0  # Use a more recent version with better ARM64 support
    platform: linux/amd64  # Ensure compatibility on ARM-based systems (e.g., Apple M1/M2)
    environment:
      MYSQL_ROOT_PASSWORD: mywebpassword  # MySQL root password
      MYSQL_DATABASE: mydb  # Database name
    volumes:
      - db_data:/var/lib/mysql  # Volume for persistent database storage
    networks:
      - mynetwork  # Connect to the custom network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  db_data:  # Named volume to persist MySQL data

networks:
  mynetwork:
    driver: bridge  # Default network driver for macOS (works well with Docker on macOS)
